name: Testing
on:
  push:
    branches: [main, dev]

jobs:
  job1_print:
    runs-on: ubuntu-latest
    steps:
      - name: Print Something
        run: |
          echo "Printing Something as job 1"
  job2_print:
    runs-on: ubuntu-latest
    needs: [job1_print]
    steps:
      - name: Print Something 2
        run: |
          echo "Printing Something as job 2"
  job3_approve:
    runs-on: ubuntu-latest
    needs: [job2_print]
    environment: deploying
    steps:
      - name: Print Something after approval
        run: |
          echo "Printing Something after approval"
